
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run the project
    init: dotnet fsi build.fsx --watch

vscode:
  extensions:
    - Ionide.Ionide-fsharp
    - EditorConfig.EditorConfig
    - PKief.material-icon-theme
    - ionutvmi.path-autocomplete

ports:
  - port: 3000
    visibility: public
    onOpen: open-preview
